pipeline{    
    agent any
    parameters {
        string(name: 'DOCKER_IMAGE_TAG', defaultValue: 'latest', description: 'Docker image tag')
        string(name: 'DOCKER_IMAGE_NAME', defaultValue: 'java-catalog', description: 'Docker image name')
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
                
            }
        }
        stage('SonarQube Analysis') {
            steps {
                script {
                    def scannerHome = tool 'sonarqube_5.0'
                    withSonarQubeEnv(installationName: 'aroldev sonarqube') {
                        sh "${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=sergio-project-kubecamp-java-catalog -Dsonar.sources=./services/go-auth -Dsonar.exclusions=**/*_test.go -Dsonar.tests=./services/go-auth -Dsonar.test.inclusions=**/*_test.go"
                    }
                }
            }
        }
        
        
        stage('Build Docker Image') {
            steps {
                dir('services/java-catalog'){
                    script{
                        def dockerImageTag = params.DOCKER_IMAGE_TAG
                        docker = docker.build("sergiolc1/java-catalog:${dockerImageTag}", '-f .docker/dockerfile .')
                    }
                }           
            }
        }
        
        stage('Push Docker Image'){
            steps {
                script {
                    withDockerRegistry(credentialsId: 'sergio.dockerhub'){
                        docker.push()
                    }
                }
            }
        }
        
    }
}